[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3

[profile.test.package."*"]
opt-level = 3

[dependencies]
itertools = "0.10.5"
rayon = "1.6.1"
